from Satellite import Satellite

A = Satellite(quaternion =[0, 0, 0, 1],angular_rate =[0.01, 0.02, 0.01], velocity=[0, -7.54, 0], position=[-7000., 0., 10.])
A.EOM.printHISTORY()
A.gravity(type = 'harmonic')
A.guidance(type="radialNED")
A.step(10000)
A.plotposition()
#A.plotvelocity()
#A.plotangularrate()
A.plotquaternions()
#A.plotSSP()
#A.plotOrbParam()
#A.plotAttitude()
A.plot()
