from Satellite import Satellite

A = Satellite(q =[0, 0, 0, 1],w =[0.1, 0.2, 0.3], velocity=[0, -7.54, 0], position=[-7000., 0., 10.])
A.gravity(type = 'harmonic')
A.guidance(type="radialNED")
A.propagation(100)
A.actuationRW(flag_RW=[True,False,False,True])
A.contQuatfeedback(kp=[10, 20, 30],kd=[100, 500, 400])
A.propagation(200)
A.actuationRW(flag_RW=[True,False,True,False])
A.propagation(10000)
A.propagation(10000)
A.step()
A.plotposition()
#A.plotvelocity()
#A.plotangularrate()
A.plotquaternions()
#A.plotSSP()
#A.plotOrbParam()
#A.plotAttitude()
A.plot()
